#!/usr/bin/env bash
# =============================================================================
# bench/report.sh — render an archived benchmark run as markdown / baseline
# =============================================================================
#
# Usage:
#   bench/report.sh [results-dir] [--stdout] [--init-baseline]
#
#   results-dir      archive directory containing results.csv and env.txt
#                    (default: newest bench/results/*/ by mtime)
#   --stdout         print the generated markdown; touch no files at all
#   --init-baseline  write bench/baseline.json from the run and exit
#
# Reads CSV v2 rows: category,name,avg,stddev,min,max,valid,dropped,
# muon_cpu_pct,muon_rss_kb. Pure bash + awk.

export LC_ALL=C
export LC_NUMERIC=C

REPORT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_DIR="$(dirname "$REPORT_DIR")"
README="$SCRIPT_DIR/README.md"
BASELINE="$REPORT_DIR/baseline.json"
START_MARK="<!-- BENCH-START -->"
END_MARK="<!-- BENCH-END -->"

DIR=""
PRINT_ONLY=0
INIT_BASELINE=0

usage() {
  echo "Usage: bench/report.sh [results-dir] [--stdout] [--init-baseline]"
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --stdout) PRINT_ONLY=1 ;;
    --init-baseline) INIT_BASELINE=1 ;;
    -h|--help) usage; exit 0 ;;
    --) shift; break ;;
    -*) echo "ERROR: unknown option: $1" >&2; usage >&2; exit 2 ;;
    *) DIR="$1" ;;
  esac
  shift
done

if [ "$PRINT_ONLY" -eq 1 ] && [ "$INIT_BASELINE" -eq 1 ]; then
  echo "ERROR: --stdout and --init-baseline are mutually exclusive" >&2
  exit 2
fi

# Default results dir: newest bench/results/*/ by mtime.
if [ -z "$DIR" ]; then
  DIR="$(ls -1dt "$REPORT_DIR"/results/*/ 2>/dev/null | head -n 1)"
  DIR="${DIR%/}"
fi

if [ -z "$DIR" ] || [ ! -f "$DIR/results.csv" ]; then
  echo "ERROR: no results.csv found${DIR:+ in '$DIR'} — pass a results dir or run the benchmark first" >&2
  exit 1
fi

SOURCE_DIR="$(cd "$DIR" && pwd)"
CREATED_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

ENV_KERNEL=""
ENV_CPU=""
if [ -f "$DIR/env.txt" ]; then
  ENV_KERNEL=$(sed -n 's/^kernel:[[:space:]]*//p' "$DIR/env.txt" | head -n 1)
  ENV_CPU=$(sed -n 's/^cpu:[[:space:]]*//p' "$DIR/env.txt" | head -n 1)
fi

# -----------------------------------------------------------------------------
# Markdown rendering (stdout). Two passes: collect baselines, then emit tables
# grouped by category; sweep lines become the capacity section.
# -----------------------------------------------------------------------------
render_markdown() {
  awk -v src="$SOURCE_DIR" -v env_kernel="$ENV_KERNEL" -v env_cpu="$ENV_CPU" '
    BEGIN {
      FS = ","
      ns = 0; nnoise = 0
      print "<!-- generated by bench/report.sh from " src " -->"
      if (env_kernel != "" || env_cpu != "") {
        print ""
        print "_Run environment: kernel " (env_kernel == "" ? "unknown" : env_kernel) \
          " | cpu " (env_cpu == "" ? "unknown" : env_cpu) "_"
      }
    }
    FNR == NR {
      if ($0 == "") next
      if ($1 ~ /^coremap:/) next
      if ($1 ~ /^sweep:/) { sweep[ns++] = $0; next }
      if ($3 == "INVALID") next
      if ($2 == "Baseline") {
        base_avg[$1] = $3 + 0
        base_sd[$1] = $4 + 0
      }
      next
    }
    $0 == "" { next }
    $1 ~ /^coremap:/ || $1 ~ /^sweep:/ { next }
    {
      cat = $1; name = $2
      if (cat != cur_cat) {
        flush_noise()
        cur_cat = cat
        print ""
        print "### Workload: " cat
        print ""
        print "| Tracer | Avg | Overhead | ±Err | Verdict | Min | Max | CleanRuns |"
        print "| :--- | ---: | ---: | ---: | :--- | ---: | ---: | ---: |"
      }
      if ($3 == "INVALID") {
        printf "| %s | INVALID | - | - | - | - | - | %s |\n", name, ($7 == "" ? "0" : $7)
        next
      }
      if (name == "Baseline") {
        printf "| %s | %s | 0.0%% | - | baseline | %s | %s | %s |\n", name, $3, $5, $6, $7
        next
      }
      if (!(cat in base_avg) || base_avg[cat] == 0) {
        printf "| %s | %s | n/a | n/a | n/a | %s | %s | %s |\n", name, $3, $5, $6, $7
        next
      }
      B = base_avg[cat]; Sb = base_sd[cat]
      avg = $3 + 0; sd = $4 + 0
      oh = (avg - B) / B * 100
      err = 100 * sqrt((sd / B) ^ 2 + (avg * Sb / (B * B)) ^ 2)
      gap = avg - B; if (gap < 0) gap = -gap
      verdict = (gap < 2 * sqrt(sd * sd + Sb * Sb)) ? "NOISE" : "REAL"
      if (verdict == "NOISE") {
        noise[nnoise++] = "\\*within noise — no measurable overhead (" name ")"
        verdict = "NOISE*"
      }
      printf "| %s | %s | %.1f%% | ±%.1f%% | %s | %s | %s | %s |\n", name, $3, oh, err, verdict, $5, $6, $7
    }
    END {
      flush_noise()
      emit_capacity()
    }
    function flush_noise(  i) {
      if (nnoise > 0) {
        print ""
        for (i = 0; i < nnoise; i++) print noise[i]
        nnoise = 0
      }
    }
    function emit_capacity(  i, j, n, f, ops, ev, st, best, bestops) {
      print ""
      print "### Capacity (sweep)"
      print ""
      if (ns == 0) {
        print "_Sweep not run in this session._"
        return
      }
      print "| Ops | Events/s | Status |"
      print "| ---: | ---: | :--- |"
      best = -1; bestops = ""
      for (i = 0; i < ns; i++) {
        n = split(sweep[i], f, " ")
        ops = "?"; ev = "?"; st = "?"
        for (j = 1; j <= n; j++) {
          if (f[j] ~ /^ops=/) ops = substr(f[j], 5)
          else if (f[j] ~ /^ev_per_s=/) ev = substr(f[j], 10)
          else if (f[j] ~ /^status=/) st = substr(f[j], 8)
        }
        printf "| %s | %s | %s |\n", ops, ev, st
        if (st == "CLEAN" && ev ~ /^[0-9]+$/ && (ev + 0) >= best) {
          best = ev + 0; bestops = ops
        }
      }
      print ""
      if (best >= 0) print "Max drop-free rate: " best " events/s at " bestops " openat ops."
      else print "Max drop-free rate: none — Muon dropped at every level."
    }
  ' "$DIR/results.csv" "$DIR/results.csv"
}

# -----------------------------------------------------------------------------
# baseline.json rendering (stdout).
# -----------------------------------------------------------------------------
render_json() {
  awk -v src="$SOURCE_DIR" -v created="$CREATED_UTC" '
    BEGIN { FS = ","; ns = 0; nk = 0 }
    $0 == "" { next }
    $1 ~ /^coremap:/ { next }
    $1 ~ /^sweep:/ { sweep[ns++] = $0; next }
    $3 == "INVALID" { next }
    {
      keys[nk] = $1 ":" $2
      rcat[nk] = $1
      rname[nk] = $2
      ravg[nk] = $3
      rsd[nk] = $4
      if ($2 == "Baseline") {
        base_avg[$1] = $3 + 0
        base_sd[$1] = $4 + 0
      }
      nk++
    }
    END {
      print "{"
      print "  \"version\": 1,"
      printf "  \"created\": \"%s\",\n", created
      printf "  \"source\": \"%s\",\n", esc(src)
      print "  \"cells\": {"
      for (i = 0; i < nk; i++) {
        cat = rcat[i]; name = rname[i]
        if (name == "Baseline") {
          oh = "0.0"; er = "0.0"
        } else if ((cat in base_avg) && base_avg[cat] != 0) {
          oh = sprintf("%.4f", (ravg[i] + 0 - base_avg[cat]) / base_avg[cat] * 100)
          er = sprintf("%.4f", 100 * sqrt(((rsd[i] + 0) / base_avg[cat]) ^ 2 + ((ravg[i] + 0) * base_sd[cat] / (base_avg[cat] * base_avg[cat])) ^ 2))
        } else {
          oh = "null"; er = "null"
        }
        printf "    \"%s\": {\"avg\": %s, \"stddev\": %s, \"overhead_pct\": %s, \"overhead_err\": %s}%s\n", esc(keys[i]), num(ravg[i]), num(rsd[i]), oh, er, (i + 1 < nk ? "," : "")
      }
      print "  },"
      best = -1
      for (i = 0; i < ns; i++) {
        n = split(sweep[i], f, " ")
        ev = ""; st = ""
        for (j = 1; j <= n; j++) {
          if (f[j] ~ /^ev_per_s=/) ev = substr(f[j], 10)
          else if (f[j] ~ /^status=/) st = substr(f[j], 8)
        }
        if (st == "CLEAN" && ev ~ /^[0-9]+$/ && (ev + 0) >= best) best = ev + 0
      }
      if (best >= 0) printf "  \"capacity_ev_per_s\": %d\n", best
      else print "  \"capacity_ev_per_s\": null"
      print "}"
    }
    function num(v) { return (v == "" || v ~ /[^0-9.eE+-]/) ? "null" : v }
    function esc(s) { gsub(/\\/, "\\\\", s); gsub(/"/, "\\\"", s); return s }
  ' "$DIR/results.csv"
}

# -----------------------------------------------------------------------------
# Replace the README block between the markers. Writes to a sibling temp file
# and renames it into place, so a failure can never corrupt README.md.
# -----------------------------------------------------------------------------
splice_readme() {
  local gen="$1" readme="$2" tmp rc
  tmp="$(mktemp "${readme}.XXXXXX")" || {
    echo "ERROR: cannot create a temp file next to $readme" >&2
    return 1
  }

  awk -v gen="$gen" -v start="$START_MARK" -v end="$END_MARK" '
    $0 == start {
      if (state != 0) { bad = 1; exit 3 }
      print
      state = 1
      while ((getline line < gen) > 0) print line
      close(gen)
      next
    }
    $0 == end {
      if (state != 1) { bad = 1; exit 4 }
      print
      state = 2
      next
    }
    state == 1 { next }
    { print }
    END { if (!bad && state != 2) exit 5 }
  ' "$readme" > "$tmp"
  rc=$?

  if [ "$rc" -eq 0 ]; then
    if mv "$tmp" "$readme"; then
      return 0
    fi
    rm -f "$tmp"
    echo "ERROR: could not replace $readme" >&2
    return 1
  fi

  rm -f "$tmp"
  case "$rc" in
    3) echo "ERROR: duplicate or misplaced BENCH-START marker in $readme" >&2 ;;
    4) echo "ERROR: duplicate or misplaced BENCH-END marker in $readme" >&2 ;;
    5) echo "ERROR: BENCH markers missing or out of order in $readme" >&2 ;;
    *) echo "ERROR: awk README splice failed (rc=$rc)" >&2 ;;
  esac
  return 1
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

if [ "$INIT_BASELINE" -eq 1 ]; then
  TMP_JSON="$(mktemp "$REPORT_DIR/baseline.json.XXXXXX")" || {
    echo "ERROR: cannot create a temp file next to baseline.json" >&2
    exit 1
  }
  if render_json > "$TMP_JSON" && mv "$TMP_JSON" "$BASELINE"; then
    echo "Baseline written to bench/baseline.json (source: $SOURCE_DIR)"
    exit 0
  fi
  rm -f "$TMP_JSON"
  echo "ERROR: failed to write $BASELINE" >&2
  exit 1
fi

TMP_MD="$(mktemp "${TMPDIR:-/tmp}/muon_bench_report.XXXXXX")" || {
  echo "ERROR: cannot create a temp file for the markdown" >&2
  exit 1
}

if ! render_markdown > "$TMP_MD"; then
  rm -f "$TMP_MD"
  echo "ERROR: failed to generate markdown from $DIR/results.csv" >&2
  exit 1
fi

if [ "$PRINT_ONLY" -eq 1 ]; then
  cat "$TMP_MD"
  rm -f "$TMP_MD"
  exit 0
fi

if [ ! -f "$README" ]; then
  rm -f "$TMP_MD"
  echo "ERROR: README not found at $README" >&2
  exit 1
fi

if ! grep -qF "$START_MARK" "$README" || ! grep -qF "$END_MARK" "$README"; then
  rm -f "$TMP_MD"
  echo "ERROR: BENCH markers missing from $README — not touching it" >&2
  exit 1
fi

if splice_readme "$TMP_MD" "$README"; then
  rm -f "$TMP_MD"
  echo "README.md updated from $SOURCE_DIR"
  exit 0
fi

rm -f "$TMP_MD"
echo "ERROR: README splice failed — README left untouched" >&2
exit 1
